import argparse
import csv
import json
import statistics
from collections import defaultdict
from pathlib import Path


SCORE_COLUMNS = (
    "correctness_1_5",
    "instruction_1_5",
    "fluency_1_5",
    "conciseness_1_5",
    "safety_1_5",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Aggregate one or more completed blind-review CSV files.")
    parser.add_argument("--input", nargs="+", required=True, help="Completed blind_review.csv files.")
    parser.add_argument("--key", required=True, help="blind_key.json generated by benchmark_zh.py")
    parser.add_argument("--out_dir", default="reports/human_review")
    return parser.parse_args()


def load_key(path: Path) -> dict[str, str]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    mapping = payload.get("candidate_to_model")
    if not isinstance(mapping, dict) or not mapping:
        raise ValueError(f"Invalid blind key: {path}")
    return {str(candidate): str(model) for candidate, model in mapping.items()}


def parse_score(raw: str, source: Path, row_number: int, column: str) -> float:
    if not str(raw).strip():
        raise ValueError(f"{source}:{row_number} has an empty {column}")
    value = float(raw)
    if not 1.0 <= value <= 5.0:
        raise ValueError(f"{source}:{row_number} {column}={value} is outside 1..5")
    return value


def load_reviews(paths: list[Path], mapping: dict[str, str]) -> list[dict]:
    rows = []
    for reviewer_index, path in enumerate(paths, 1):
        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            reader = csv.DictReader(handle)
            required = {"item_id", "category", "candidate", *SCORE_COLUMNS}
            missing = required - set(reader.fieldnames or [])
            if missing:
                raise ValueError(f"{path} is missing columns: {sorted(missing)}")
            for row_number, row in enumerate(reader, 2):
                candidate = str(row["candidate"]).strip()
                if candidate not in mapping:
                    raise ValueError(f"{path}:{row_number} has unknown candidate {candidate!r}")
                scores = {
                    column: parse_score(row[column], path, row_number, column)
                    for column in SCORE_COLUMNS
                }
                rows.append(
                    {
                        "reviewer": reviewer_index,
                        "item_id": row["item_id"],
                        "category": row["category"],
                        "candidate": candidate,
                        "model": mapping[candidate],
                        "mean_score": statistics.fmean(scores.values()),
                        **scores,
                    }
                )
    if not rows:
        raise ValueError("No completed review rows found")
    return rows


def aggregate(rows: list[dict]) -> tuple[list[dict], list[dict]]:
    by_model = defaultdict(list)
    by_model_category = defaultdict(list)
    for row in rows:
        by_model[row["model"]].append(row)
        by_model_category[(row["model"], row["category"])].append(row)

    overall = []
    for model, group in sorted(by_model.items()):
        item = {
            "model": model,
            "ratings": len(group),
            "reviewers": len({row["reviewer"] for row in group}),
            "human_score_1_5": round(statistics.fmean(row["mean_score"] for row in group), 4),
        }
        for column in SCORE_COLUMNS:
            item[column] = round(statistics.fmean(row[column] for row in group), 4)
        overall.append(item)

    categories = []
    for (model, category), group in sorted(by_model_category.items()):
        categories.append(
            {
                "model": model,
                "category": category,
                "ratings": len(group),
                "human_score_1_5": round(statistics.fmean(row["mean_score"] for row in group), 4),
                **{
                    column: round(statistics.fmean(row[column] for row in group), 4)
                    for column in SCORE_COLUMNS
                },
            }
        )
    return overall, categories


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        return
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def write_report(path: Path, overall: list[dict], categories: list[dict]) -> None:
    lines = [
        "# Human Blind Review",
        "",
        "## Overall",
        "",
        "| Model | Human | Correctness | Instruction | Fluency | Conciseness | Safety | Ratings | Reviewers |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in overall:
        lines.append(
            f"| {row['model']} | {row['human_score_1_5']:.3f} | "
            f"{row['correctness_1_5']:.3f} | {row['instruction_1_5']:.3f} | "
            f"{row['fluency_1_5']:.3f} | {row['conciseness_1_5']:.3f} | "
            f"{row['safety_1_5']:.3f} | {row['ratings']} | {row['reviewers']} |"
        )

    lines.extend(
        [
            "",
            "## Categories",
            "",
            "| Model | Category | Human | Correctness | Instruction | Fluency | Conciseness | Safety |",
            "|---|---|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for row in categories:
        lines.append(
            f"| {row['model']} | {row['category']} | {row['human_score_1_5']:.3f} | "
            f"{row['correctness_1_5']:.3f} | {row['instruction_1_5']:.3f} | "
            f"{row['fluency_1_5']:.3f} | {row['conciseness_1_5']:.3f} | "
            f"{row['safety_1_5']:.3f} |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    input_paths = [Path(path) for path in args.input]
    mapping = load_key(Path(args.key))
    rows = load_reviews(input_paths, mapping)
    overall, categories = aggregate(rows)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(out_dir / "human_summary.csv", overall)
    write_csv(out_dir / "human_by_category.csv", categories)
    write_report(out_dir / "human_report.md", overall, categories)

    print(f"Wrote human review summary to {out_dir}")
    for row in overall:
        print(
            f"{row['model']}: human={row['human_score_1_5']:.3f}, "
            f"correctness={row['correctness_1_5']:.3f}, "
            f"instruction={row['instruction_1_5']:.3f}"
        )


if __name__ == "__main__":
    main()
